In [1]:
import erlab
import erlab.analysis as era
import erlab.interactive as eri
import erlab.plotting as eplt
import matplotlib.pyplot as plt
import numpy as np
import xarray as xr

#xr.set_options(keep_attrs=True)

In [2]:
xr.set_options(keep_attrs=True)
#Prevent the automatic removal of metadata attributes when performing operations on DataArray or Dataset objec

What are Attributes?
In xarray, attributes (attrs) are metadata dictionaries attached to a DataArray or a Dataset.  They contain key-value pairs that describe the data, but aren't part of the data values themselves. For example, a DataArray representing temperature might have attrs like {'units': 'Celsius', 'long_name': 'Air Temperature'}.

By default, when you perform an operation that combines or modifies data, such as adding two DataArrays together, xarray will often drop these attributes. This behavior is by design because it's difficult to automatically determine what the correct attributes for the new, combined data should be. For instance, if you add temperature and pressure data, what should the units attribute of the result be? To avoid ambiguity and potential errors, xarray plays it safe and discards the attributes.

# Reading & writing data
In ERLabPy, data are represented as xarray.DataArray, xarray.Dataset, and xarray.DataTree objects.

In [1]:
# C:/Users/mdram/SolidStatePhysics1/dataverse_files/S313_MgB2_0001.txt

In [14]:
import pandas as pd
import xarray as xr

# Read the data from the text file into a pandas DataFrame
df = pd.read_csv("C:/Users/mdram/SolidStatePhysics1/dataverse_files/S313_MgB2_0001.txt")

# Convert the pandas DataFrame to an Xarray Dataset
data = xr.Dataset.from_dataframe(df)
data
# You can now work with the data in the Xarray Dataset objecdata)

<xarray.Dataset> Size: 3kB
Dimensions:  (index: 215)
Coordinates:
  * index    (index) int64 2kB 0 1 2 3 4 5 6 7 ... 208 209 210 211 212 213 214
Data variables:
    [Info]   (index) object 2kB 'Instrument=' ... '2.396900\t1958.000000\t186...

In [ ]:
import pandas as pd

data = pd.read_csv('C:/Users/mdram/SolidStatePhysics1/dataverse_files/S313_MgB2_0001.txt', header= None)
print(data)

In [ ]:
import IPython.display

#displaying all the data points
IPython.display.HTML(data.to_html())

In [ ]:
# For a comma-separated file
import numpy as np
data = np.genfromtxt('C:/Users/mdram/SolidStatePhysics1/dataverse_files/S313_MgB2_0001.txt', delimiter=',', dtype=None, names=True, encoding='utf-8')

Use np.genfromtxt() with dtype=None and names=True. This tells NumPy to automatically infer the data types from the content and read the first row as column names. This is the most robust and flexible approach for heterogeneous data.

In [ ]:
import xarray as xr

xr.set_options(display_expand_data=False)

In [15]:
from erlab.io.exampledata import generate_data
dat = generate_data(seed=1)
dat

<xarray.DataArray (kx: 250, ky: 250, eV: 300)> Size: 150MB
array([[[7.62263759e+00, 7.79669012e+00, 8.54899927e+00, ...,
         7.43998539e-02, 2.87192764e-01, 1.17162298e-01],
        [5.77109615e+00, 5.41021008e+00, 8.13189986e+00, ...,
         1.19740882e-01, 4.41123091e-01, 2.87550787e-01],
        [3.69988336e+00, 6.13047827e+00, 9.26550765e+00, ...,
         3.27216347e-02, 1.24345727e-01, 9.74753847e-02],
        ...,
        [1.03793110e+01, 9.39206767e+00, 7.86329045e+00, ...,
         5.67224279e-03, 6.93701682e-02, 2.55449306e-01],
        [9.45192597e+00, 9.28969689e+00, 8.15860877e+00, ...,
         2.62516806e-03, 9.35377159e-02, 4.58775631e-01],
        [8.47861698e+00, 7.83535029e+00, 7.99401967e+00, ...,
         6.45067175e-04, 2.35049190e-02, 1.15617709e-01]],

       [[5.16086529e+00, 8.15225454e+00, 7.13746052e+00, ...,
         2.29056728e-01, 7.88172712e-01, 3.74986154e-01],
        [5.53050089e+00, 7.05423323e+00, 8.02861979e+00, ...,
         1.37411435e-01, 3.74809063e-01, 7.89947333e-01],
        [6.46176888e+00, 7.54329005e+00, 9.11179445e+00, ...,
         5.34462431e-02, 1.56022307e-01, 3.22295753e-01],
...
         3.77927412e-02, 1.48428345e-01, 3.82262830e-02],
        [7.06003753e+00, 7.92235718e+00, 8.53247386e+00, ...,
         4.32444030e-02, 2.88144869e-02, 5.11212296e-03],
        [8.10163402e+00, 9.36495926e+00, 9.93007676e+00, ...,
         1.84027122e-01, 4.57339889e-02, 7.78105102e-04]],

       [[8.17228090e+00, 5.64489198e+00, 7.38363241e+00, ...,
         9.14295677e-01, 2.97993566e-01, 3.50371902e-01],
        [9.60641499e+00, 7.85398455e+00, 6.62176566e+00, ...,
         1.89974543e-01, 6.04698207e-02, 7.10149876e-02],
        [9.73356538e+00, 8.33776784e+00, 8.46285240e+00, ...,
         2.19420479e-02, 1.57718325e-03, 2.85064834e-03],
        ...,
        [1.15284926e+01, 1.16738122e+01, 1.04812349e+01, ...,
         9.58888799e-02, 3.84565652e-01, 9.90532353e-02],
        [8.23054347e+00, 8.05153463e+00, 7.36956031e+00, ...,
         2.37258867e-02, 9.15559784e-02, 2.31511024e-02],
        [1.02414068e+01, 1.15566061e+01, 1.08599121e+01, ...,
         3.61126311e-03, 2.12009878e-03, 3.69104683e-04]]],
      shape=(250, 250, 300))
Coordinates:
  * kx       (kx) float64 2kB -0.89 -0.8829 -0.8757 ... 0.8757 0.8829 0.89
  * ky       (ky) float64 2kB -0.89 -0.8829 -0.8757 ... 0.8757 0.8829 0.89
  * eV       (eV) float64 2kB -0.45 -0.4482 -0.4464 ... 0.08639 0.08819 0.09

In [ ]:
import erlab.interactive as eri
eri.itool(dat)

In [16]:
import os
import glob
import pandas as pd
import xarray as xr

# Get the current working directory where your script and data files are located
directory_path = os.getcwd()

# Use glob to find all files that match the pattern, and sort them numerically
file_list = sorted(glob.glob(os.path.join(directory_path, "S313_MgB2_*.txt")))

# A list to hold the individual datasets
datasets = []

# Loop through each file in the sorted list
for file_path in file_list:
    # Read the file content to find the header information
    with open(file_path, 'r') as f:
        lines = f.readlines()

    # Find the line where the [Data] section begins
    data_start_line = None
    for i, line in enumerate(lines):
        if "[Data]" in line:
            data_start_line = i + 1
            # Extract the angle value from the line that is 3 lines before [Data]
            angle_value = float(lines[i - 3].strip())
            break
            
    if data_start_line is None:
        print(f"Warning: [Data] section not found in {file_path}. Skipping.")
        continue

    # Read the data section into a pandas DataFrame, skipping the header lines
    df = pd.read_csv(file_path, sep='\t', header=None, skiprows=data_start_line)
    
    # Create an Xarray DataArray from the DataFrame
    # Column 0 is the energy, and the angle is our new coordinate
    data_array = xr.DataArray(
        data=df.iloc[:, 1:],  # All columns except the first one
        dims=('energy', 'y_pixel'),
        coords={
            'energy': df.iloc[:, 0],
            'angle': angle_value,
        }
    )
    
    # Add a dimension for the angle
    data_array = data_array.expand_dims('angle')
    
    datasets.append(data_array)

# Combine all DataArrays into a single Xarray Dataset along the 'angle' dimension
combined_data = xr.concat(datasets, dim='angle')

# You can now access and plot the full dataset
print("Combined Dataset:")
print(combined_data)

# You can now plot the full dataset
# combined_data['intensity'].plot(x='angle', y='energy')

ValueError: must supply at least one object to concatenate

In [18]:
import os
import glob
import pandas as pd
import xarray as xr

# Define the directory where your files are located.
# This is the path you provided. You must change this line if your files are in a different folder.
directory_path = "C:/Users/mdram/SolidStatePhysics1/dataverse_files"

# Use glob to find all files that match the pattern, and sort them numerically
file_list = sorted(glob.glob(os.path.join(directory_path, "S313_MgB2_*.txt")))

# A list to hold the individual datasets
datasets = []

if not file_list:
    print(f"Error: No files found in the directory: {directory_path}")
else:
    # Loop through each file in the sorted list
    for file_path in file_list:
        # Read the file content to find the header information
        with open(file_path, 'r') as f:
            lines = f.readlines()
            
        # Find the line where the [Data] section begins
        data_start_line = None
        angle_value = None
        for i, line in enumerate(lines):
            if "[Data]" in line:
                data_start_line = i + 1
                # The angle value is consistently located a few lines before the [Data] marker
                angle_line = lines[i - 3].strip()
                angle_value = float(angle_line)
                break
        
        if data_start_line is None or angle_value is None:
            print(f"Warning: [Data] section or angle value not found in {file_path}. Skipping.")
            continue

        # Read the data section into a pandas DataFrame, skipping the header lines
        df = pd.read_csv(file_path, sep='\t', header=None, skiprows=data_start_line)
        
        # Create an Xarray DataArray from the DataFrame
        data_array = xr.DataArray(
            data=df.iloc[:, 1:],  # All columns except the first one
            dims=('energy', 'y_pixel'),
            coords={
                'energy': df.iloc[:, 0],
                'angle': angle_value,
            }
        )
        
        # Add a dimension for the angle
        data_array = data_array.expand_dims('angle')
        
        datasets.append(data_array)

# Combine all DataArrays into a single Xarray Dataset along the 'angle' dimension
if datasets:
    combined_data = xr.concat(datasets, dim='angle', join='outer')

    print("Combined Dataset:")
    print(combined_data)

    # You can now plot the full dataset
    # combined_data['intensity'].plot(x='angle', y='energy')
else:
    print("No datasets were created. Please check your file path and file names.")

Combined Dataset:
<xarray.DataArray (angle: 122, energy: 500, y_pixel: 400)> Size: 195MB
array([[[6.91790e+04, 7.53530e+04, 8.30350e+04, ..., 1.86172e+05,
         1.79517e+05, 1.71785e+05],
        [7.18980e+04, 7.78270e+04, 7.93850e+04, ..., 1.87110e+05,
         1.74664e+05, 1.61242e+05],
        [7.41690e+04, 7.81500e+04, 8.21640e+04, ..., 1.82655e+05,
         1.71396e+05, 1.66788e+05],
        ...,
        [1.87500e+03, 2.21900e+03, 2.13700e+03, ..., 1.61600e+03,
         1.88200e+03, 1.62300e+03],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [1.95800e+03, 1.86300e+03, 2.06200e+03, ..., 1.81400e+03,
         1.67900e+03, 1.02100e+03]],

       [[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
              

In [19]:
# To see a summary of the dataset
print(combined_data)

<xarray.DataArray (angle: 122, energy: 500, y_pixel: 400)> Size: 195MB
array([[[6.91790e+04, 7.53530e+04, 8.30350e+04, ..., 1.86172e+05,
         1.79517e+05, 1.71785e+05],
        [7.18980e+04, 7.78270e+04, 7.93850e+04, ..., 1.87110e+05,
         1.74664e+05, 1.61242e+05],
        [7.41690e+04, 7.81500e+04, 8.21640e+04, ..., 1.82655e+05,
         1.71396e+05, 1.66788e+05],
        ...,
        [1.87500e+03, 2.21900e+03, 2.13700e+03, ..., 1.61600e+03,
         1.88200e+03, 1.62300e+03],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [1.95800e+03, 1.86300e+03, 2.06200e+03, ..., 1.81400e+03,
         1.67900e+03, 1.02100e+03]],

       [[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         na

In [24]:
import numpy as np

# Assuming you have the following information from your experimental setup:
# The first pixel corresponds to a momentum of -1.0 Angstroms^-1
first_pixel_momentum = -1.0
# The last pixel corresponds to a momentum of 1.0 Angstroms^-1
last_pixel_momentum = 1.0

# Create a linearly spaced array for the new 'ky' coordinate
ky_values = np.linspace(first_pixel_momentum, last_pixel_momentum, combined_data.sizes['y_pixel'])
# Assuming your dataset is named 'combined_data'
#combined_data = combined_data.rename({'angle': 'kx'})
# Add the new 'ky' coordinate to your dataset.
# The `y_pixel` dimension will now have a `ky` coordinate.
combined_data = combined_data.assign_coords(ky=('y_pixel', ky_values))

# Now, when you print the dataset, 'y_pixel' will have a coordinate
combined_data

<xarray.DataArray (kx: 122, energy: 500, y_pixel: 400)> Size: 195MB
array([[[6.91790e+04, 7.53530e+04, 8.30350e+04, ..., 1.86172e+05,
         1.79517e+05, 1.71785e+05],
        [7.18980e+04, 7.78270e+04, 7.93850e+04, ..., 1.87110e+05,
         1.74664e+05, 1.61242e+05],
        [7.41690e+04, 7.81500e+04, 8.21640e+04, ..., 1.82655e+05,
         1.71396e+05, 1.66788e+05],
        ...,
        [1.87500e+03, 2.21900e+03, 2.13700e+03, ..., 1.61600e+03,
         1.88200e+03, 1.62300e+03],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [1.95800e+03, 1.86300e+03, 2.06200e+03, ..., 1.81400e+03,
         1.67900e+03, 1.02100e+03]],

       [[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
...
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [1.27000e+02, 5.50000e+01, 2.22000e+02, ..., 3.30000e+01,
         4.90000e+01, 1.20000e+02],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan]],

       [[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [6.20000e+01, 1.02000e+02, 1.63000e+02, ..., 5.30000e+01,
         8.00000e+00, 0.00000e+00],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan]]], shape=(122, 500, 400))
Coordinates:
  * energy   (energy) float64 4kB 2.0 2.002 2.004 2.007 ... 2.395 2.396 2.397
  * kx       (kx) float64 976B 0.0 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0
    ky       (y_pixel) float64 3kB -1.0 -0.995 -0.99 -0.985 ... 0.99 0.995 1.0
Dimensions without coordinates: y_pixel

In [21]:
# To see all the coordinates in your dataset
print(combined_data.coords)

Coordinates:
  * energy   (energy) float64 4kB 2.0 2.002 2.004 2.007 ... 2.395 2.396 2.397
  * angle    (angle) float64 976B 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0
    ky       (y_pixel) float64 3kB -1.0 -0.995 -0.99 -0.985 ... 0.99 0.995 1.0


In [25]:
import os
import glob

# Define the directory where your files are located
directory_path = "C:/Users/mdram/SolidStatePhysics1/dataverse_files"

# Use glob to find all files and sort them
file_list = sorted(glob.glob(os.path.join(directory_path, "S313_MgB2_*.txt")))

print("Checking angle values for all files:")
print("-" * 30)

for file_path in file_list:
    try:
        with open(file_path, 'r') as f:
            lines = f.readlines()
        
        # Find the line with the [Data] marker
        data_line_index = next(i for i, line in enumerate(lines) if "[Data]" in line)
        
        # Extract the value from 3 lines above [Data]
        angle_line = lines[data_line_index - 3].strip()
        angle_value = float(angle_line)
        
        # Print the file and the value
        print(f"File: {os.path.basename(file_path)} -> Angle: {angle_value}")
        
    except (ValueError, IndexError):
        print(f"Warning: Could not parse angle for {os.path.basename(file_path)}. Skipping.")

Checking angle values for all files:
------------------------------
File: S313_MgB2_0001.txt -> Angle: 0.0
File: S313_MgB2_0002.txt -> Angle: 0.0
File: S313_MgB2_0003.txt -> Angle: 0.0
File: S313_MgB2_0004.txt -> Angle: 0.0
File: S313_MgB2_0005.txt -> Angle: 0.0
File: S313_MgB2_0006.txt -> Angle: 0.0
File: S313_MgB2_0007.txt -> Angle: 0.0
File: S313_MgB2_0008.txt -> Angle: 0.0
File: S313_MgB2_0009.txt -> Angle: 0.0
File: S313_MgB2_0010.txt -> Angle: 0.0
File: S313_MgB2_0011.txt -> Angle: 0.0
File: S313_MgB2_0012.txt -> Angle: 0.0
File: S313_MgB2_0013.txt -> Angle: 0.0
File: S313_MgB2_0014.txt -> Angle: 0.0
File: S313_MgB2_0015.txt -> Angle: 0.0
File: S313_MgB2_0016.txt -> Angle: 0.0
File: S313_MgB2_0017.txt -> Angle: 0.0
File: S313_MgB2_0018.txt -> Angle: 0.0
File: S313_MgB2_0019.txt -> Angle: 0.0
File: S313_MgB2_0020.txt -> Angle: 0.0
File: S313_MgB2_0021.txt -> Angle: 0.0
File: S313_MgB2_0022.txt -> Angle: 0.0
File: S313_MgB2_0023.txt -> Angle: 0.0
File: S313_MgB2_0024.txt -> Angle: 

In [3]:
import os
import glob
import pandas as pd
import xarray as xr

def load_ses_spectra(directory_path, file_pattern="S313_MgB2_*.txt"):
    """
    Loads and combines multiple ARPES spectra files from a specified directory
    into a single xarray dataset.

    Args:
        directory_path (str): The path to the directory containing the data files.
        file_pattern (str): The file pattern to match (e.g., "S313_MgB2_*.txt").

    Returns:
        xarray.DataArray: A single DataArray containing the combined ARPES data.
    """
    # Find all files that match the pattern, and sort them
    file_list = sorted(glob.glob(os.path.join(directory_path, file_pattern)))

    if not file_list:
        raise FileNotFoundError(f"No files found in the directory: {directory_path} with pattern {file_pattern}")

    datasets = []
    
    for file_path in file_list:
        with open(file_path, 'r') as f:
            lines = f.readlines()
        
        data_start_line = None
        angle_value = None
        for i, line in enumerate(lines):
            if "[Data]" in line:
                data_start_line = i + 1
                angle_line = lines[i - 3].strip()
                try:
                    angle_value = float(angle_line)
                except ValueError:
                    print(f"Warning: Could not parse angle from line '{angle_line}' in {os.path.basename(file_path)}. Skipping.")
                    angle_value = None
                break
        
        if data_start_line is None or angle_value is None:
            continue

        df = pd.read_csv(file_path, sep='\t', header=None, skiprows=data_start_line)
        
        data_array = xr.DataArray(
            data=df.iloc[:, 1:],
            dims=('energy', 'y_pixel'),
            coords={
                'energy': df.iloc[:, 0],
                'angle': angle_value,
            }
        ).expand_dims('angle')
        
        datasets.append(data_array)

    if not datasets:
        raise ValueError("No valid datasets were created. Check file format.")

    combined_data = xr.concat(datasets, dim='angle', join='outer')
    
    return combined_data

# Example of how to use your new function:
if __name__ == '__main__':
    # You must provide the correct path to your data folder
    data_folder = "C:/Users/mdram/SolidStatePhysics1/dataverse_files"
    
    try:
        # Call the function to load and combine your data
        arpes_data = load_ses_spectra(data_folder)
        
        # Now you can inspect and work with the dataset
        print(arpes_data)

    except (FileNotFoundError, ValueError) as e:
        print(f"Error: {e}")

<xarray.DataArray (angle: 122, energy: 500, y_pixel: 400)> Size: 195MB
array([[[6.91790e+04, 7.53530e+04, 8.30350e+04, ..., 1.86172e+05,
         1.79517e+05, 1.71785e+05],
        [7.18980e+04, 7.78270e+04, 7.93850e+04, ..., 1.87110e+05,
         1.74664e+05, 1.61242e+05],
        [7.41690e+04, 7.81500e+04, 8.21640e+04, ..., 1.82655e+05,
         1.71396e+05, 1.66788e+05],
        ...,
        [1.87500e+03, 2.21900e+03, 2.13700e+03, ..., 1.61600e+03,
         1.88200e+03, 1.62300e+03],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [1.95800e+03, 1.86300e+03, 2.06200e+03, ..., 1.81400e+03,
         1.67900e+03, 1.02100e+03]],

       [[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         na

In [6]:
combined_data

NameError: name 'combined_data' is not defined

In [4]:
import numpy as np
import xarray as xr

# Assuming 'combined_data' is your dataset object

# 1. Rename the 'angle' coordinate to 'kx'
#    This makes the dataset physically intuitive.
combined_data = combined_data.rename({'angle': 'kx'})

# 2. Assign a 'ky' coordinate to the 'y_pixel' dimension
#    Replace the example values with your own from the experiment
first_pixel_momentum = -1.0 # Example value
last_pixel_momentum = 1.0   # Example value

ky_values = np.linspace(first_pixel_momentum, last_pixel_momentum, combined_data.sizes['y_pixel'])
combined_data = combined_data.assign_coords(ky=('y_pixel', ky_values))

# Now, when you print the dataset, it will have the correct coordinates
print(combined_data)

NameError: name 'combined_data' is not defined

In [7]:
import os
import glob
import pandas as pd
import xarray as xr
import numpy as np

def load_ses_spectra(directory_path, file_pattern="S313_MgB2_*.txt"):
    """
    Loads and combines multiple ARPES spectra files from a specified directory
    into a single xarray dataset with correct physical coordinates.

    Args:
        directory_path (str): The path to the directory containing the data files.
        file_pattern (str): The file pattern to match (e.g., "S313_MgB2_*.txt").

    Returns:
        xarray.DataArray: A single DataArray containing the combined ARPES data,
                          with coordinates labeled 'energy', 'kx', and 'ky'.
    """
    file_list = sorted(glob.glob(os.path.join(directory_path, file_pattern)))

    if not file_list:
        raise FileNotFoundError(f"No files found in the directory: {directory_path} with pattern {file_pattern}")

    datasets = []
    
    for file_path in file_list:
        with open(file_path, 'r') as f:
            lines = f.readlines()
        
        data_start_line = None
        angle_value = None
        for i, line in enumerate(lines):
            if "[Data]" in line:
                data_start_line = i + 1
                angle_line = lines[i - 3].strip()
                try:
                    angle_value = float(angle_line)
                except ValueError:
                    print(f"Warning: Could not parse angle from line '{angle_line}' in {os.path.basename(file_path)}. Skipping.")
                    angle_value = None
                break
        
        if data_start_line is None or angle_value is None:
            continue

        df = pd.read_csv(file_path, sep='\t', header=None, skiprows=data_start_line)
        
        data_array = xr.DataArray(
            data=df.iloc[:, 1:],
            dims=('energy', 'y_pixel'),
            coords={
                'energy': df.iloc[:, 0],
                'angle': angle_value,
            }
        ).expand_dims('angle')
        
        datasets.append(data_array)

    if not datasets:
        raise ValueError("No valid datasets were created. Check file format.")

    # Combine all DataArrays and explicitly use join='outer' to prevent future errors
    combined_data = xr.concat(datasets, dim='angle', join='outer')
    
    # 1. Rename the 'angle' coordinate to 'kx' for physical clarity
    combined_data = combined_data.rename({'angle': 'kx'})
    
    # 2. Assign a new 'ky' coordinate to the 'y_pixel' dimension
    #    You MUST replace these values with your actual experimental parameters!
    first_pixel_momentum = -1.0
    last_pixel_momentum = 1.0
    
    ky_values = np.linspace(first_pixel_momentum, last_pixel_momentum, combined_data.sizes['y_pixel'])
    combined_data = combined_data.assign_coords(ky=('y_pixel', ky_values))
    
    return combined_data

# Example of how to use your new function:
if __name__ == '__main__':
    # You must provide the correct path to your data folder
    data_folder = "C:/Users/mdram/SolidStatePhysics1/dataverse_files"
    
    try:
        # Call the function to load and combine your data
        arpes_data = load_ses_spectra(data_folder)
        
        # Now you can inspect and work with the dataset
        print("Successfully created the combined ARPES dataset:")
        print(arpes_data)

    except (FileNotFoundSrror, ValueError) as e:
        print(f"Error: {e}")

Successfully created the combined ARPES dataset:
<xarray.DataArray (kx: 122, energy: 500, y_pixel: 400)> Size: 195MB
array([[[6.91790e+04, 7.53530e+04, 8.30350e+04, ..., 1.86172e+05,
         1.79517e+05, 1.71785e+05],
        [7.18980e+04, 7.78270e+04, 7.93850e+04, ..., 1.87110e+05,
         1.74664e+05, 1.61242e+05],
        [7.41690e+04, 7.81500e+04, 8.21640e+04, ..., 1.82655e+05,
         1.71396e+05, 1.66788e+05],
        ...,
        [1.87500e+03, 2.21900e+03, 2.13700e+03, ..., 1.61600e+03,
         1.88200e+03, 1.62300e+03],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [1.95800e+03, 1.86300e+03, 2.06200e+03, ..., 1.81400e+03,
         1.67900e+03, 1.02100e+03]],

       [[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,

In [8]:
import os
import glob
import pandas as pd
import xarray as xr
import numpy as np

def load_ses_spectra(directory_path, file_pattern="S313_MgB2_*.txt"):
    """
    Loads and combines multiple ARPES spectra files from a specified directory
    into a single xarray dataset with correct physical coordinates.

    Args:
        directory_path (str): The path to the directory containing the data files.
        file_pattern (str): The file pattern to match (e.g., "S313_MgB2_*.txt").

    Returns:
        xarray.DataArray: A single DataArray containing the combined ARPES data,
                          with coordinates labeled 'energy', 'kx', and 'ky'.
    """
    file_list = sorted(glob.glob(os.path.join(directory_path, file_pattern)))

    if not file_list:
        raise FileNotFoundError(f"No files found in the directory: {directory_path} with pattern {file_pattern}")

    datasets = []
    
    for file_path in file_list:
        with open(file_path, 'r') as f:
            lines = f.readlines()
        
        data_start_line = None
        angle_value = None
        for i, line in enumerate(lines):
            # Find the line where the [Data] section begins
            if "[Data]" in line:
                data_start_line = i + 1
                
                # We know the angle value is 3 lines before the [Data] line.
                # Use a more robust check to find the correct line with a float value.
                try:
                    angle_value = float(lines[i - 3].strip())
                except (ValueError, IndexError):
                    # If parsing fails, fall back to the next line which also contains a float value
                    try:
                        angle_value = float(lines[i - 4].strip())
                    except (ValueError, IndexError):
                        print(f"Warning: Could not parse angle in {os.path.basename(file_path)}. Skipping.")
                        angle_value = None
                break
        
        if data_start_line is None or angle_value is None:
            continue

        df = pd.read_csv(file_path, sep='\t', header=None, skiprows=data_start_line)
        
        data_array = xr.DataArray(
            data=df.iloc[:, 1:],
            dims=('energy', 'y_pixel'),
            coords={
                'energy': df.iloc[:, 0],
                'angle': angle_value,
            }
        ).expand_dims('angle')
        
        datasets.append(data_array)

    if not datasets:
        raise ValueError("No valid datasets were created. Check file format.")

    combined_data = xr.concat(datasets, dim='angle', join='outer')
    
    combined_data = combined_data.rename({'angle': 'kx'})
    
    first_pixel_momentum = -1.0 # REPLACE THIS WITH YOUR REAL VALUE
    last_pixel_momentum = 1.0   # REPLACE THIS WITH YOUR REAL VALUE
    
    ky_values = np.linspace(first_pixel_momentum, last_pixel_momentum, combined_data.sizes['y_pixel'])
    combined_data = combined_data.assign_coords(ky=('y_pixel', ky_values))
    
    return combined_data

# Example of how to use your new function:
if __name__ == '__main__':
    data_folder = "C:/Users/mdram/SolidStatePhysics1/dataverse_files"
    
    try:
        arpes_data = load_ses_spectra(data_folder)
        print("Successfully created the combined ARPES dataset:")
        print(arpes_data)

    except (FileNotFoundError, ValueError) as e:
        print(f"Error: {e}")

Successfully created the combined ARPES dataset:
<xarray.DataArray (kx: 122, energy: 500, y_pixel: 400)> Size: 195MB
array([[[6.91790e+04, 7.53530e+04, 8.30350e+04, ..., 1.86172e+05,
         1.79517e+05, 1.71785e+05],
        [7.18980e+04, 7.78270e+04, 7.93850e+04, ..., 1.87110e+05,
         1.74664e+05, 1.61242e+05],
        [7.41690e+04, 7.81500e+04, 8.21640e+04, ..., 1.82655e+05,
         1.71396e+05, 1.66788e+05],
        ...,
        [1.87500e+03, 2.21900e+03, 2.13700e+03, ..., 1.61600e+03,
         1.88200e+03, 1.62300e+03],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [1.95800e+03, 1.86300e+03, 2.06200e+03, ..., 1.81400e+03,
         1.67900e+03, 1.02100e+03]],

       [[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,

In [9]:
combined_data

NameError: name 'combined_data' is not defined

In [10]:
# Assuming your script is named 'my_arpes_loader.py' and contains the function.
# You must specify the path to your data folder.
data_folder = "C:/Users/mdram/SolidStatePhysics1/dataverse_files"

# The function returns a single object
arpes_data = load_ses_spectra(data_folder)

In [12]:
arpes_data

<xarray.DataArray (kx: 122, energy: 500, y_pixel: 400)> Size: 195MB
array([[[6.91790e+04, 7.53530e+04, 8.30350e+04, ..., 1.86172e+05,
         1.79517e+05, 1.71785e+05],
        [7.18980e+04, 7.78270e+04, 7.93850e+04, ..., 1.87110e+05,
         1.74664e+05, 1.61242e+05],
        [7.41690e+04, 7.81500e+04, 8.21640e+04, ..., 1.82655e+05,
         1.71396e+05, 1.66788e+05],
        ...,
        [1.87500e+03, 2.21900e+03, 2.13700e+03, ..., 1.61600e+03,
         1.88200e+03, 1.62300e+03],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [1.95800e+03, 1.86300e+03, 2.06200e+03, ..., 1.81400e+03,
         1.67900e+03, 1.02100e+03]],

       [[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
...
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [1.27000e+02, 5.50000e+01, 2.22000e+02, ..., 3.30000e+01,
         4.90000e+01, 1.20000e+02],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan]],

       [[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [6.20000e+01, 1.02000e+02, 1.63000e+02, ..., 5.30000e+01,
         8.00000e+00, 0.00000e+00],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan]]], shape=(122, 500, 400))
Coordinates:
  * energy   (energy) float64 4kB 2.0 2.002 2.004 2.007 ... 2.395 2.396 2.397
  * kx       (kx) float64 976B 0.0 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0
    ky       (y_pixel) float64 3kB -1.0 -0.995 -0.99 -0.985 ... 0.99 0.995 1.0
Dimensions without coordinates: y_pixel

In [13]:
import os
import glob
import pandas as pd
import xarray as xr
import numpy as np
from tqdm import tqdm

def load_ses_spectra(directory_path, file_pattern="S313_MgB2_*.txt"):
    """
    Loads and combines multiple ARPES spectra files and their metadata.
    """
    file_list = sorted(glob.glob(os.path.join(directory_path, file_pattern)))
    if not file_list:
        raise FileNotFoundError("No files found.")

    datasets = []
    metadata_list = []

    for file_path in tqdm(file_list, desc="Loading Spectra"):
        with open(file_path, 'r') as f:
            header_lines = []
            for line in f:
                header_lines.append(line)
                if "[Data]" in line:
                    break
        
        # Parse metadata from the header
        header_dict = {
            'hv': float([line for line in header_lines if "Excitation Energy=" in line][0].split('=')[-1].strip()) if [line for line in header_lines if "Excitation Energy=" in line] else np.nan,
            'pass_energy': float([line for line in header_lines if "Pass Energy=" in line][0].split('=')[-1].strip().split()[1]) if [line for line in header_lines if "Pass Energy=" in line] else np.nan,
            'lens_mode': [line for line in header_lines if "Lens Mode=" in line][0].split('=')[-1].strip() if [line for line in header_lines if "Lens Mode=" in line] else None,
            # Add more metadata fields as needed
        }

        # Find the start of the data section
        data_start_line = None
        for i, line in enumerate(header_lines):
            if "[Data]" in line:
                data_start_line = i + 1
                break

        df = pd.read_csv(file_path, sep='\t', header=None, skiprows=data_start_line)
        
        angle_value = float(header_lines[data_start_line - 4].strip())
        
        data_array = xr.DataArray(
            data=df.iloc[:, 1:],
            dims=('energy', 'y_pixel'),
            coords={
                'energy': df.iloc[:, 0],
                'angle': angle_value,
            },
            attrs=header_dict,
        ).expand_dims('angle')
        
        datasets.append(data_array)
        metadata_list.append(header_dict)

    combined_data = xr.concat(datasets, dim='angle', join='outer')
    
    return combined_data

In [14]:
import numpy as np

# Load your data using the updated function
# arpes_data = load_ses_spectra("C:/Users/mdram/SolidStatePhysics1/dataverse_files")

# 1. Rename the dimensions to match your example
arpes_data = arpes_data.rename({'energy': 'eV', 'angle': 'alpha', 'y_pixel': 'beta'})

# 2. Assign the 'beta' and 'alpha' coordinates
#    You must replace these values with your actual experimental parameters
alpha_values = np.linspace(-15.0, 15.0, arpes_data.sizes['alpha'])
arpes_data = arpes_data.assign_coords(alpha=alpha_values)

beta_values = np.linspace(2.0, 7.0, arpes_data.sizes['beta'])
arpes_data = arpes_data.assign_coords(beta=beta_values)

# 3. Add single-value coordinates from your example
arpes_data = arpes_data.assign_coords({
    'delta': xr.DataArray(0.0),
    'xi': xr.DataArray(0.0),
    'hv': xr.DataArray(50.0),
    'polarization': xr.DataArray(0, dtype=int),
    'sample_temp': xr.DataArray(20.0),
    'X': xr.DataArray(0.0),
    'Y': xr.DataArray(0.0),
    'Z': xr.DataArray(0.0),
})

# 4. Add the attributes (metadata) to the dataset
arpes_data.attrs['LensMode'] = 'Angular30'
arpes_data.attrs['SpectrumType'] = 'Fixed'
arpes_data.attrs['PassEnergy'] = 10
arpes_data.attrs['Date'] = '10/09/2025'
arpes_data.attrs['Time'] = '04:34:08 AM'
arpes_data.attrs['configuration'] = 1
arpes_data.attrs['sample_workfunction'] = 4.3
arpes_data.attrs['data_loader_name'] = 'example'

# Now, when you print the dataset, it will look like the example
print(arpes_data)

ValueError: cannot rename 'angle' because it is not a variable or dimension in this dataset

In [15]:
print(arpes_data.coords)

Coordinates:
  * energy   (energy) float64 4kB 2.0 2.002 2.004 2.007 ... 2.395 2.396 2.397
  * kx       (kx) float64 976B 0.0 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0
    ky       (y_pixel) float64 3kB -1.0 -0.995 -0.99 -0.985 ... 0.99 0.995 1.0


In [16]:
# Assuming your dataset is named 'arpes_data'
if 'angle' in arpes_data.coords:
    arpes_data = arpes_data.rename({'angle': 'kx'})

# Now you can proceed with other operations, as the coordinate is now named 'kx'
print(arpes_data.coords)

Coordinates:
  * energy   (energy) float64 4kB 2.0 2.002 2.004 2.007 ... 2.395 2.396 2.397
  * kx       (kx) float64 976B 0.0 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0
    ky       (y_pixel) float64 3kB -1.0 -0.995 -0.99 -0.985 ... 0.99 0.995 1.0


In [18]:
arpes_data

<xarray.DataArray (kx: 122, energy: 500, y_pixel: 400)> Size: 195MB
array([[[6.91790e+04, 7.53530e+04, 8.30350e+04, ..., 1.86172e+05,
         1.79517e+05, 1.71785e+05],
        [7.18980e+04, 7.78270e+04, 7.93850e+04, ..., 1.87110e+05,
         1.74664e+05, 1.61242e+05],
        [7.41690e+04, 7.81500e+04, 8.21640e+04, ..., 1.82655e+05,
         1.71396e+05, 1.66788e+05],
        ...,
        [1.87500e+03, 2.21900e+03, 2.13700e+03, ..., 1.61600e+03,
         1.88200e+03, 1.62300e+03],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [1.95800e+03, 1.86300e+03, 2.06200e+03, ..., 1.81400e+03,
         1.67900e+03, 1.02100e+03]],

       [[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
...
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [1.27000e+02, 5.50000e+01, 2.22000e+02, ..., 3.30000e+01,
         4.90000e+01, 1.20000e+02],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan]],

       [[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [6.20000e+01, 1.02000e+02, 1.63000e+02, ..., 5.30000e+01,
         8.00000e+00, 0.00000e+00],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan]]], shape=(122, 500, 400))
Coordinates:
  * energy   (energy) float64 4kB 2.0 2.002 2.004 2.007 ... 2.395 2.396 2.397
  * kx       (kx) float64 976B 0.0 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0
    ky       (y_pixel) float64 3kB -1.0 -0.995 -0.99 -0.985 ... 0.99 0.995 1.0
Dimensions without coordinates: y_pixel

In [20]:
import pathlib
import re

import erlab

erlab.io.load(5).qplot()

ValueError: No loader has been set. Set a loader with `erlab.io.set_loader` first